name: SemVer Tags

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  tag:
    runs-on: size/small
    steps:
      - uses: actions/checkout@v3
      - uses: vweevers/additional-tags-action@v2
